"""Bundle tests for multi-file dependency resolution and merged emit.

Stage A: physical merge + per-module prefix; NO cross-module symbol rewiring.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from any2enforce import transpile_bundle
from any2enforce.bundle.resolver import Resolver, qn_to_ns_prefix

HERE = Path(__file__).parent
FIXTURES = HERE / "bundle_fixtures"


# ======================================================================
# Positive: bundle output structure
# ======================================================================


def test_bundle_sibling_import():
    """Entry with ``import util``: both modules present; each has its prefix."""
    entry = str(FIXTURES / "main_import.py")
    modules, text, diag = transpile_bundle(entry)
    assert diag.errors == [], [d.code for d in diag.errors]

    # Both modules present: main_import + util
    assert len(modules) == 2
    qns = {m.name for m in modules}
    assert "main_import" in qns
    assert "util" in qns

    # Dependency order: util before main_import
    assert modules[0].name == "util"
    assert modules[1].name == "main_import"

    # Each has ns_prefix
    assert modules[0].ns_prefix == "util_"
    assert modules[1].ns_prefix == "main_import_"

    # Merged output contains both with prefixed names
    assert "int util_helper(int x)" in text or "int util_helper" in text
    assert "int main_import_run" in text

    # Bundle header present
    assert "Generated by any2enforce -- DO NOT EDIT" in text
    assert "Bundle: merged from:" in text
    assert "util.py" in text
    assert "main_import.py" in text


def test_bundle_from_import():
    """Entry with ``from util import helper``: still resolves and prefixes."""
    entry = str(FIXTURES / "main_from_import.py")
    modules, text, diag = transpile_bundle(entry)
    assert diag.errors == [], [d.code for d in diag.errors]

    assert len(modules) == 2
    assert modules[0].name == "util"
    assert modules[1].name == "main_from_import"

    # Prefixes applied
    assert modules[0].ns_prefix == "util_"
    assert "int util_helper" in text
    assert "int main_from_import_run" in text


def test_bundle_as_alias():
    """Entry with ``import util as ut``: alias import is preserved."""
    entry = str(FIXTURES / "main_alias.py")
    modules, text, diag = transpile_bundle(entry)
    assert diag.errors == [], [d.code for d in diag.errors]

    assert len(modules) == 2
    # util is still resolved; alias is in the import comment
    assert "util" in {m.name for m in modules}
    assert "import util (ut)" in text


def test_bundle_package():
    """Entry importing from a package (pkg.core via pkg/__init__.py)."""
    entry = str(FIXTURES / "main_pkg.py")
    modules, text, diag = transpile_bundle(entry)
    assert diag.errors == [], [d.code for d in diag.errors]

    qns = {m.name for m in modules}
    assert "pkg" in qns          # __init__.py
    assert "pkg.core" in qns     # core module

    # Per-module prefix: pkg_ and pkg_core_
    mod_map = {m.name: m for m in modules}
    assert mod_map["pkg"].ns_prefix == "pkg_"
    assert mod_map["pkg.core"].ns_prefix == "pkg_core_"

    # Output has prefixed names
    assert "float pkg_core_compute" in text


def test_bundle_dependency_order():
    """Modules appear in topological order (deps before dependents)."""
    entry = str(FIXTURES / "main_import.py")
    modules, _, diag = transpile_bundle(entry)
    assert diag.errors == [], [d.code for d in diag.errors]

    names = [m.name for m in modules]
    # util has no deps (other than builtins), main_import depends on util
    util_idx = names.index("util")
    main_idx = names.index("main_import")
    assert util_idx < main_idx


# ======================================================================
# Negative: diagnostics
# ======================================================================


def test_bundle_unresolved_import():
    """Unresolvable import produces a diagnostic (no crash)."""
    entry = str(FIXTURES / "unresolved_main.py")
    modules, text, diag = transpile_bundle(entry)
    # Should have at least one unresolved import error
    assert any(d.code == "bundle-unresolved-import" for d in diag.errors), \
        [d.code for d in diag.errors]
    # Entry module itself is still returned
    assert modules


def test_bundle_cycle_detection():
    """Detect import cycle and produce diagnostic (no infinite loop)."""
    entry = str(FIXTURES / "cycle_a.py")
    modules, text, diag = transpile_bundle(entry)
    # Cycle diagnostic should be present
    assert any(d.code == "bundle-cycle" for d in diag.errors), \
        [d.code for d in diag.errors]
    # Should not crash -- runs to completion


def test_bundle_entry_not_found():
    """Missing entry file produces diagnostic."""
    _, _, diag = transpile_bundle("nonexistent_entry.py")
    assert any(d.code == "bundle-not-found" for d in diag.errors), \
        [d.code for d in diag.errors]


# ======================================================================
# Unit: resolver internals
# ======================================================================


def test_qn_to_ns_prefix():
    assert qn_to_ns_prefix("a") == "a_"
    assert qn_to_ns_prefix("a.b.c") == "a_b_c_"
    assert qn_to_ns_prefix("pkg.module") == "pkg_module_"


def test_resolver_sibling_import():
    from any2enforce.diagnostics import DiagnosticSink
    r = Resolver(DiagnosticSink())
    modules = r.resolve_closure(str(FIXTURES / "main_import.py"))
    assert len(modules) == 2
    names = {m.name for m in modules}
    assert names == {"main_import", "util"}