"""Negative tests: unsupported Python constructs must produce error
diagnostics and visible markers in the output — never silent wrong code."""

import pytest

from any2enforce import transpile


@pytest.mark.parametrize("source,code", [
    ("def f():\n    try:\n        pass\n    except Exception:\n        pass\n",
     "unsupported-try-except"),
    ("def f():\n    with open('x') as fh:\n        pass\n",
     "unsupported-with-statement"),
    ("f = lambda x: x + 1\n", "unsupported-lambda-closures"),
    ("def f():\n    def g():\n        return 1\n    return g()\n",
     "unsupported-nested-function"),
    ("def f():\n    yield 1\n", "unsupported-yield"),
    ("def f(*args):\n    pass\n", "varargs"),
    ("class A:\n    pass\nclass B(A, A):\n    pass\n",
     "multiple-inheritance"),
])
def test_unsupported_constructs_error(source, code):
    _, text, diag = transpile(source, filename="bad.py")
    assert diag.errors, f"expected at least one error diagnostic for {source!r}"
    if code:
        assert any(d.code.startswith(code) for d in diag.errors), \
            [d.code for d in diag.errors]
    # generated output must not be silent: it carries an error or TODO marker
    assert ("[any2enforce" in text) or ("TODO[" in text), text


def test_comprehension_in_call_is_lifted():
    """Nested comps are lifted to temps before the call (no comp-expr)."""
    src = "def f(xs: list[int]) -> None:\n    print([x for x in xs])\n"
    _, text, diag = transpile(src, filename="ok.py")
    assert diag.errors == []
    assert "Print(_pyLift0);" in text
    assert "_pyLift0.Insert(x);" in text


def test_module_entry_guard_is_reported():
    src = ('if __name__ == "__main__":\n    print("hi")\n')
    _, text, diag = transpile(src, filename="main.py")
    assert any(d.level == "warning" or d.level == "error" for d in diag.items)


def test_empty_module_emits_valid_skeleton():
    _, text, diag = transpile("# nothing here\n", filename="empty.py")
    assert diag.errors == []
    assert "Generated by any2enforce" in text
