"""EnforceScript backend: IR -> EnforceScript (.c) source text.

All EnforceScript-specific syntax lives here. Every ⚠-marked mapping is
rendered conservatively and documented in docs/VERIFY.md; the Workbench
validation loop (validate/workbench.py) is the source of truth for them.
"""

from __future__ import annotations

from typing import Dict, List, Optional

from ..diagnostics import DiagnosticSink
from ..ir import (
    AUTO, BOOL, FLOAT, INT, STRING, VOID, AnnAssignStmt, ArrayType,
    AssignStmt, AttributeExpr, AugAssignStmt, BoolOpExpr, BinOpExpr,
    BreakStmt, CallExpr, ClassDef, CompareExpr, ConstExpr, ContinueStmt,
    DictExpr, ErrorType, Expr, ExprStmt, ForStmt, FunctionDef, IfStmt,
    ImportStmt, JoinedStrExpr, ListExpr, MapType, MethodDef, Module, NameExpr,
    PassStmt, RangeForStmt, ReturnStmt, ScalarType, SetType, Span, Stmt,
    SubscriptExpr, TernaryExpr, Type, UnaryOpExpr, UnsupportedExpr,
    UnsupportedStmt, WhileStmt,
)

RESERVED = {
    "class", "modded", "sealed", "proto", "native", "external", "override",
    "ref", "auto", "typename", "vector", "bool", "float", "int", "string",
    "enum", "typedef", "static", "protected", "private", "public", "new",
    "delete", "null", "true", "false", "return", "if", "else", "while", "do",
    "for", "foreach", "switch", "case", "default", "break", "continue",
    "this", "super", "void", "const", "out", "in", "function", "not",
    "and", "or", "is", "init",
}


class EnforceBackend:
    def __init__(self, config: dict, diagnostics: DiagnosticSink) -> None:
        self.config = config
        self.diag = diagnostics
        self.naming = config.get("naming", {})
        self.policy = self.naming.get("policy", "keep")
        self.field_prefix = self.naming.get("field_prefix", "m_")
        self.visibility = config.get("visibility", "protected")
        self.lines: List[str] = []
        self.indent = 0
        self._field_names: set = set()
        self._method_names: set = set()
        self._locals: Dict[str, Type] = {}
        self._declared: set = set()  # names already declared in current function

    # ==================================================================
    # entry
    # ==================================================================
    def emit(self, mod: Module) -> str:
        self.lines = []
        self.indent = 0
        self._line(f"// Generated by any2enforce v0.1 -- DO NOT EDIT")
        self._line(f"// Source: {mod.name}.py (Python -> EnforceScript)")
        self._line("")
        if mod.doc:
            self._emit_doc_comment(mod.doc)
        for imp in mod.imports:
            names = ", ".join(imp.names) if imp.names else ""
            self._line(f"// import {imp.module}" + (f" ({names})" if names else ""))
        if mod.imports:
            self._line("")
        for g in mod.globals:
            self._stmt(g)
            self._line("")
        for fn in mod.functions:
            self._emit_function(fn)
            self._line("")
        for cls in mod.classes:
            self._emit_class(cls)
            self._line("")
        # drop trailing blank lines
        while self.lines and self.lines[-1] == "":
            self.lines.pop()
        return "\n".join(self.lines) + "\n"

    # ==================================================================
    # declarations
    # ==================================================================
    def _emit_function(self, fn: FunctionDef) -> None:
        self._locals = getattr(fn, "locals", None) or {}
        self._declared = set()
        ret = self._type(fn.return_type or VOID)
        if fn.doc:
            self._emit_doc_comment(fn.doc)
        self._line(f"{ret} {self._fn_id(fn.name)}({self._params(fn.params)})")
        self._emit_todos(fn.todos)
        self._emit_body(fn.body)

    def _emit_class(self, cls: ClassDef) -> None:
        self._field_names = {f.name for f in cls.fields}
        self._method_names = {m.name for m in cls.methods}
        if cls.doc:
            self._emit_doc_comment(cls.doc)
        head = f"class {self._type_id(cls.name)}"
        if cls.bases:
            head += " : " + ", ".join(self._type_id(b) for b in cls.bases)
        self._line(head)
        self._emit_todos(cls.todos)
        self._line("{")
        self.indent += 1
        if cls.fields:
            for f in cls.fields:
                default = self._field_default(f.type)
                note = ""
                if f.default is not None:
                    note = f"  // was initialized to {self._const(f.default)} in Python"
                self._line(f"{self.visibility} {self._type(f.type)} {self._field_id(f.name)};{note}")
            self._line("")
        for i, m in enumerate(cls.methods):
            if i:
                self._line("")
            self._emit_method(cls, m)
        self.indent -= 1
        self._line("}")
        self._field_names = set()
        self._method_names = set()

    def _emit_method(self, cls: ClassDef, m: MethodDef) -> None:
        self._locals = getattr(m, "locals", None) or {}
        self._declared = {p.name for p in m.params}
        if m.is_constructor:
            name = self._type_id(cls.name)
            ret = "void"
        else:
            name = self._fn_id(m.name)
            ret = self._type(m.return_type or VOID)
        if m.doc:
            self._emit_doc_comment(m.doc)
        static = "static " if m.is_static and not m.is_constructor else ""
        self._line(f"{static}{ret} {name}({self._params(m.params)})")
        self._emit_todos(m.todos)
        self._emit_body(m.body)

    def _params(self, params) -> str:
        out = []
        for p in params:
            decl = f"{self._type(p.type or AUTO)} {self._var_id(p.name)}"
            if p.default is not None:
                decl += f" = {self._const(p.default)}"
            out.append(decl)
        return ", ".join(out)

    # ==================================================================
    # statements
    # ==================================================================
    def _emit_body(self, body: List[Stmt]) -> None:
        self._line("{")
        self.indent += 1
        if not body:
            self._line("// (empty body from Python 'pass' / docstring)")
        for stmt in body:
            self._stmt(stmt)
        self.indent -= 1
        self._line("}")

    def _stmt(self, stmt: Stmt) -> None:
        if isinstance(stmt, AssignStmt):
            self._assign(stmt)
        elif isinstance(stmt, AnnAssignStmt):
            if isinstance(stmt.target, NameExpr):
                t = stmt.type or AUTO
                self._declared.add(stmt.target.name)
                self._line(f"{self._type(t)} {self._var_id(stmt.target.name)}"
                           f"{' = ' + self._expr(stmt.value) if stmt.value else ''};")
            else:
                self._line(f"{self._expr(stmt.target)} = {self._expr(stmt.value)};"
                           if stmt.value else f"{self._expr(stmt.target)} = 0;")
        elif isinstance(stmt, AugAssignStmt):
            self._aug_assign(stmt)
        elif isinstance(stmt, ExprStmt):
            if isinstance(stmt.expr, UnsupportedExpr):
                self._line(f"// [any2enforce:error] {stmt.expr.reason}")
            else:
                self._line(f"{self._expr(stmt.expr)};")
        elif isinstance(stmt, ReturnStmt):
            if stmt.value is None:
                self._line("return;")
            elif isinstance(stmt.value, TernaryExpr):
                self._ternary_return(stmt.value)
            else:
                self._line(f"return {self._expr(stmt.value)};")
        elif isinstance(stmt, IfStmt):
            self._if(stmt)
        elif isinstance(stmt, WhileStmt):
            self._line(f"while ({self._expr(stmt.cond)})")
            self._emit_body(stmt.body)
        elif isinstance(stmt, RangeForStmt):
            self._range_for(stmt)
        elif isinstance(stmt, ForStmt):
            self._foreach(stmt)
        elif isinstance(stmt, BreakStmt):
            self._line("break;")
        elif isinstance(stmt, ContinueStmt):
            self._line("continue;")
        elif isinstance(stmt, PassStmt):
            self._line("// pass")
        elif isinstance(stmt, ImportStmt):
            self._line(f"// import {stmt.module}")
        elif isinstance(stmt, UnsupportedStmt):
            self._line(f"// [any2enforce:{stmt.level}] unsupported: {stmt.reason}")
            if stmt.source_text:
                for src in stmt.source_text.splitlines():
                    self._line(f"//   {src}")
        else:
            self._line(f"// [any2enforce:error] unhandled statement {type(stmt).__name__}")

    def _assign(self, stmt: AssignStmt) -> None:
        if isinstance(stmt.target, NameExpr) and isinstance(stmt.value, DictExpr):
            self._map_literal(stmt.target, stmt.value)
            return
        if isinstance(stmt.value, ListExpr):
            self._list_assign(stmt)
            return
        if isinstance(stmt.value, TernaryExpr):
            self._ternary_assign(stmt)
            return
        target = self._expr(stmt.target)
        value = self._expr(stmt.value)
        if isinstance(stmt.target, NameExpr):
            if stmt.target.name in self._declared:
                self._line(f"{target} = {value};")
            else:
                self._declared.add(stmt.target.name)
                self._line(f"auto {target} = {value};")
        else:
            self._line(f"{target} = {value};")

    def _list_assign(self, stmt: AssignStmt) -> None:
        """array literal -> `array<T> x = { ... };` (verified syntax:
        `array<Class> attributes = {};`, `testSuites = {testSuite};`)"""
        items = ", ".join(self._expr(i) for i in stmt.value.items)
        lit = f"{{ {items} }}"
        if isinstance(stmt.target, NameExpr):
            name = self._var_id(stmt.target.name)
            t = stmt.value.type if isinstance(stmt.value.type, ArrayType) else None
            if t is None:
                self.diag.error(
                    "list-type",
                    "cannot infer list element type; annotate the variable, "
                    "e.g. `xs: list[int] = [...]`",
                    stmt.value.span,
                )
                t = ArrayType(FLOAT)
            if stmt.target.name in self._declared:
                self._line(f"{name} = {lit};")
            else:
                self._declared.add(stmt.target.name)
                self._line(f"{self._type(t)} {name} = {lit};")
        else:
            self._line(f"{self._expr(stmt.target)} = {lit};")

    def _map_literal(self, target: NameExpr, d: DictExpr) -> None:
        """dict literal -> `map<K,V> name = new map<K,V>(); name[k] = v; ...`
        (map subscript `[]` read/write verified against Reforger scripts)"""
        kt, vt = self._dict_types(d)
        if kt is None or vt is None:
            self.diag.error(
                "dict-type",
                "cannot infer dict key/value types (annotate the variable, "
                "e.g. `config: dict[str, int] = ...`)",
                d.span,
            )
            kt, vt = kt or FLOAT, vt or FLOAT
        name = self._var_id(target.name)
        decl = f"map<{kt.render()}, {vt.render()}> {name} = new map<{kt.render()}, {vt.render()}>();"
        if target.name in self._declared:
            self._line(f"{name} = new map<{kt.render()}, {vt.render()}>();")
        else:
            self._declared.add(target.name)
            self._line(decl)
        for k, v in d.items:
            self._line(f"{name}[{self._expr(k)}] = {self._expr(v)};")

    def _ternary_assign(self, stmt: AssignStmt) -> None:
        """`x = a if c else b` -> `T x = b; if (c) { x = a; }`
        (EnforceScript has NO ternary operator - verified)"""
        t = stmt.value
        if isinstance(stmt.target, NameExpr) and stmt.target.name not in self._declared:
            self._declared.add(stmt.target.name)
            self._line(f"auto {self._var_id(stmt.target.name)} = {self._expr(t.if_false)};")
        else:
            self._line(f"{self._expr(stmt.target)} = {self._expr(t.if_false)};")
        self._line(f"if ({self._expr(t.cond)})")
        self._emit_body([AssignStmt(stmt.target, t.if_true, span=stmt.span)])

    def _ternary_return(self, t: TernaryExpr) -> None:
        self._line(f"if ({self._expr(t.cond)})")
        self._line("{")
        self.indent += 1
        self._line(f"return {self._expr(t.if_true)};")
        self.indent -= 1
        self._line("}")
        self._line("else")
        self._line("{")
        self.indent += 1
        self._line(f"return {self._expr(t.if_false)};")
        self.indent -= 1
        self._line("}")

    def _aug_assign(self, stmt: AugAssignStmt) -> None:
        t = self._expr(stmt.target)
        v = self._expr(stmt.value)
        if stmt.op == "//":
            self._line(f"{t} = Math.Floor({t} / {v});")
        elif stmt.op == "**":
            self._line(f"{t} = Math.Pow({t}, {v});")
        elif stmt.op in ("+", "-", "*", "/", "%"):
            self._line(f"{t} {stmt.op}= {v};")
        else:
            self._line(f"// [any2enforce:error] unsupported augmented operator '{stmt.op}'")

    def _if(self, stmt: IfStmt) -> None:
        for i, (cond, body) in enumerate(stmt.branches):
            kw = "if" if i == 0 else "else if"
            self._line(f"{kw} ({self._expr(cond)})")
            self._emit_body(body)
        if stmt.orelse:
            self._line("else")
            self._emit_body(stmt.orelse)

    def _range_for(self, stmt: RangeForStmt) -> None:
        var = self._var_id(stmt.target.name)
        lo, hi = stmt.lo, stmt.hi
        temps: List[str] = []
        for label, e in (("lo", lo), ("hi", hi)):
            if not _is_simple(e):
                tmp = f"_pyRange{len(temps)}"
                self._line(f"int {tmp} = {self._expr(e)};")
                temps.append(tmp)
                if label == "lo":
                    lo = NameExpr(tmp)
                else:
                    hi = NameExpr(tmp)
        step = stmt.step
        if step is None or (isinstance(step, ConstExpr) and step.value == 1):
            cond = f"{var} < {self._expr(hi)}"
            inc = f"{var}++"
        elif isinstance(step, ConstExpr) and isinstance(step.value, int) and step.value > 1:
            cond = f"{var} < {self._expr(hi)}"
            inc = f"{var} += {step.value}"
        elif isinstance(step, ConstExpr) and isinstance(step.value, int) and step.value < 0:
            cond = f"{var} > {self._expr(hi)}"
            inc = f"{var} -= {-step.value}"
        else:
            self.diag.error(
                "range-step",
                "range() with non-constant step is not supported in v0.1",
                step.span if step else stmt.span,
            )
            cond = f"{var} < {self._expr(hi)}"
            inc = f"{var}++"
        self._line(f"for (int {var} = {self._expr(lo)}; {cond}; {inc})")
        self._declared.add(stmt.target.name)
        self._emit_body(stmt.body)

    def _foreach(self, stmt: ForStmt) -> None:
        t = stmt.elem_type
        if isinstance(t, ErrorType):
            render = "auto"
        elif t is None:
            render = "auto"
            self.diag.error(
                "foreach-type", "missing foreach element type", stmt.span)
        else:
            render = self._type(t)
        self._line(f"foreach ({render} {self._var_id(stmt.target.name)} : "
                   f"{self._expr(stmt.iterable)})")
        self._declared.add(stmt.target.name)
        self._emit_body(stmt.body)

    # ==================================================================
    # expressions
    # ==================================================================
    def _expr(self, e: Expr) -> str:
        if isinstance(e, NameExpr):
            return self._var_id(e.name)
        if isinstance(e, ConstExpr):
            return self._const(e)
        if isinstance(e, BinOpExpr):
            return self._binop(e)
        if isinstance(e, BoolOpExpr):
            joiner = " && " if e.op == "and" else " || "
            return joiner.join(self._p(v) for v in e.values)
        if isinstance(e, CompareExpr):
            parts = []
            left = e.left
            for op, right in zip(e.ops, e.comparators):
                r = self._p(right)
                if op == "is":
                    if isinstance(right, ConstExpr) and right.value is None:
                        parts.append(f"{self._p(left)} == null")
                    else:
                        self.diag.warning(
                            "is-identity",
                            "'is' identity comparison mapped to '=='",
                            e.span,
                        )
                        parts.append(f"{self._p(left)} == {r}")
                elif op == "is not":
                    if isinstance(right, ConstExpr) and right.value is None:
                        parts.append(f"{self._p(left)} != null")
                    else:
                        self.diag.warning(
                            "is-identity",
                            "'is not' identity comparison mapped to '!='",
                            e.span,
                        )
                        parts.append(f"{self._p(left)} != {r}")
                elif op in ("in", "not in"):
                    # verified: array.Contains (V06), map.Contains (P09),
                    # string.Contains (string.c API) — all compile & run
                    container = right
                    t = self._expr_type(container)
                    if t is None:
                        self.diag.warning(
                            "in-type",
                            "membership test on unknown type; emitted as "
                            ".Contains() (verify it exists on the type)",
                            e.span,
                        )
                    contained = f"{self._p(container)}.Contains({self._p(left)})"
                    parts.append(f"!{contained}" if op == "not in" else contained)
                else:
                    parts.append(f"{self._p(left)} {op} {r}")
                left = right
            return " && ".join(parts)
        if isinstance(e, UnaryOpExpr):
            if e.op == "not":
                return f"!{self._p(e.operand)}"
            return f"-{self._p(e.operand)}"
        if isinstance(e, CallExpr):
            return self._call(e)
        if isinstance(e, AttributeExpr):
            return self._attr_access(e)
        if isinstance(e, SubscriptExpr):
            base = self._expr(e.value)
            idx = self._expr(e.index)
            # map/array/string all support [] in EnforceScript (verified)
            return f"{base}[{idx}]"
        if isinstance(e, ListExpr):
            self.diag.error(
                "list-expr",
                "array literal `[...]` is only supported in assignment in v0.1 "
                "(EnforceScript `{ ... }` is a declaration initializer, not a "
                "general expression)",
                e.span,
            )
            return "/* [any2enforce:error] array literal in expression */ 0"
        if isinstance(e, DictExpr):
            self.diag.error(
                "dict-expr",
                "dict literal is only supported as a direct assignment value in v0.1",
                e.span,
            )
            return "new map<float, float>()"
        if isinstance(e, JoinedStrExpr):
            return self._fstring(e)
        if isinstance(e, TernaryExpr):
            self.diag.error(
                "ternary-expr",
                "ternary `a if c else b` in expression context is not supported "
                "in v0.1 (EnforceScript has no ternary); use it as a standalone "
                "assignment or return",
                e.span,
            )
            return "0"
        if isinstance(e, UnsupportedExpr):
            return f"/* [any2enforce:error] {e.reason} */ 0"
        return "/* [any2enforce:error] unhandled expression */ 0"

    def _binop(self, e: BinOpExpr) -> str:
        l, r = self._p(e.left), self._p(e.right)
        if e.op == "//":
            return f"Math.Floor({l} / {r})"
        if e.op == "**":
            return f"Math.Pow({l}, {r})"
        if e.op == "%":
            lt, rt = self._expr_type(e.left), self._expr_type(e.right)
            if lt is STRING:
                return self._py_string_format(e.left, e.right)
            if lt is INT and rt is INT:
                return f"{l} % {r}"  # int modulo (verified: `x % 360`)
            if lt is FLOAT or rt is FLOAT:
                return f"Math.Mod({l}, {r})"  # float modulo (Math.Mod verified)
            return f"{l} % {r}"
        return f"{l} {e.op} {r}"

    def _py_string_format(self, fmt_expr: Expr, val_expr: Expr) -> str:
        """Python old-style `"..." % x` -> string.Format() (verified API)."""
        if isinstance(fmt_expr, ConstExpr) and isinstance(fmt_expr.value, str):
            fmt, n = _convert_py_format(fmt_expr.value)
            if n == 0:
                return f'"{_escape(fmt)}"'
            if n > 1:
                self.diag.warning(
                    "py-format-multi",
                    "multi-value % formatting needs a tuple; only the first "
                    "placeholder is filled in v0.1",
                    fmt_expr.span,
                )
            return f'string.Format("{_escape(fmt)}", {self._expr(val_expr)})'
        self.diag.warning(
            "py-format",
            "non-literal format string in % formatting; emitted as string.Format()",
            fmt_expr.span,
        )
        return f'string.Format({self._expr(fmt_expr)}, {self._expr(val_expr)})'

    def _call(self, e: CallExpr) -> str:
        if e.kwargs:
            self.diag.error(
                "call-kwargs",
                "keyword arguments in calls are not supported in v0.1",
                e.span,
                note="pass arguments positionally",
            )
        args: List[str] = []
        for a in e.args:
            if isinstance(a, ListExpr):
                # verified: inline array literal as call argument (V05:
                # `Sum({1, 2, 3})` compiles and returns 6)
                items = ", ".join(self._expr(i) for i in a.items)
                args.append(f"{{ {items} }}")
            else:
                args.append(self._expr(a))
        if isinstance(e.func, NameExpr):
            name = e.func.name
            if name == "print":
                return self._print_call(e, args)
            if name == "len":
                return self._len_call(e, args)
            if name == "str":
                return self._str_call(e, args)
            if name == "int":
                return f"(int)({args[0]})" if args else "(int)(0)"
            if name == "float":
                return f"(float)({args[0]})" if args else "(float)(0)"
            if name == "bool":
                self.diag.warning(
                    "bool-cast",
                    "'bool(x)' mapped to 'x != 0' (approximation)",
                    e.span,
                )
                return f"({args[0]} != 0)" if args else "false"
            if name == "range":
                self.diag.error(
                    "range-expr",
                    "range() outside a for-loop is not supported in v0.1",
                    e.span,
                )
                return "0"
            if name == "abs":
                return self._abs_call(e, args)
            if name in ("min", "max"):
                return self._minmax_call(e, name, args)
            if name == "sum":
                self.diag.error(
                    "builtin-sum",
                    "sum() is not supported in v0.1 (expand the loop manually)",
                    e.span,
                )
                return "0"
            if name == "super":
                self.diag.error(
                    "unsupported-super",
                    "bare super() is not supported; only super().method(...) "
                    "and super().__init__(...) are handled",
                    e.span,
                )
                return "0"
            return f"{self._fn_id(name)}({', '.join(args)})"
        if isinstance(e.func, AttributeExpr):
            if _is_super_expr(e.func.value):
                # super().method(...) -> super.Method(...) (verified: 1357 files)
                return f"super.{self._method_id(e.func.attr)}({', '.join(args)})"
            if isinstance(e.func.value, NameExpr) and e.func.value.name == "this":
                # self.method(...) -> bare method call (verified convention)
                return f"{self._method_id(e.func.attr)}({', '.join(args)})"
            obj = self._expr(e.func.value)
            meth = self._method_id(e.func.attr)
            return f"{obj}.{meth}({', '.join(args)})"
        return f"/* [any2enforce:error] unsupported callee */ 0"

    def _str_call(self, e: CallExpr, args: List[str]) -> str:
        """str(x) -> x (string) / x.ToString() (int/float) / string.ToString(x)."""
        if not args:
            return '""'
        t = self._expr_type(e.args[0])
        if t is STRING:
            return args[0]
        if t is INT or t is FLOAT:
            return f"{args[0]}.ToString()"
        return f"string.ToString({args[0]})"

    def _abs_call(self, e: CallExpr, args: List[str]) -> str:
        if not args:
            return "0"
        t = self._expr_type(e.args[0])
        if t is INT:
            return f"Math.AbsInt({args[0]})"  # verified: Math.AbsInt, not Math.Abs
        if t is FLOAT:
            return f"Math.AbsFloat({args[0]})"  # verified: Math.AbsFloat
        self.diag.error(
            "abs-type",
            "abs() needs an int or float argument in v0.1",
            e.span,
        )
        return f"Math.AbsFloat({args[0]})"

    def _minmax_call(self, e: CallExpr, name: str, args: List[str]) -> str:
        if len(args) != 2:
            self.diag.error(
                f"builtin-{name}",
                f"{name}() with != 2 arguments is not supported in v0.1",
                e.span,
            )
            return "0"
        t0 = self._expr_type(e.args[0])
        t1 = self._expr_type(e.args[1])
        if t0 is INT and t1 is INT:
            fn = "Math.MinInt" if name == "min" else "Math.MaxInt"
        else:
            fn = "Math.Min" if name == "min" else "Math.Max"
        return f"{fn}({args[0]}, {args[1]})"

    def _print_call(self, e: CallExpr, args: List[str]) -> str:
        """print(...) -> Print(x) / PrintFormat("%1 %2 ...", a, b)
        (verified: `proto void Print(void var, ...)`, `proto void
        PrintFormat(string fmt, void param1..param9 = NULL, ...)`)"""
        if not args:
            return 'Print("")'
        if len(args) == 1:
            return f"Print({args[0]})"
        if len(args) <= 9:
            parts = " ".join(f"%{i+1}" for i in range(len(args)))
            return f'PrintFormat("{parts}", {", ".join(args)})'
        self.diag.error(
            "print-arity",
            "print() with more than 9 arguments is not supported in v0.1",
            e.span,
        )
        parts = " ".join(f"%{i+1}" for i in range(9))
        return f'PrintFormat("{parts}", {", ".join(args[:9])})'

    def _len_call(self, e: CallExpr, args: List[str]) -> str:
        if not args:
            return "0"
        arg = e.args[0]
        arg_type = self._expr_type(arg)
        if isinstance(arg_type, ArrayType) or isinstance(arg_type, (MapType, SetType)):
            return f"{args[0]}.Count()"
        if arg_type is STRING:
            return f"{args[0]}.Length()"
        self.diag.error(
            "len-type",
            "len() on an unknown type; mapped to .Count() (verify)",
            e.span,
        )
        return f"{args[0]}.Count()"

    def _fstring(self, e: JoinedStrExpr) -> str:
        """f-string -> string.Format("...%1...", args) (verified API:
        `static proto string Format(string fmt, void param1..param9 = NULL)`)"""
        fmt = ""
        args: List[str] = []
        n = 0
        for is_expr, part in e.parts:
            if is_expr:
                n += 1
                fmt += f"%{n}"
                args.append(self._expr(part))
            else:
                fmt += part
        if n == 0:
            return f'"{_escape(fmt)}"'
        return f'string.Format("{_escape(fmt)}", {", ".join(args)})'

    # ==================================================================
    # identifiers / atoms
    # ==================================================================
    def _attr_access(self, e: AttributeExpr) -> str:
        if _is_super_expr(e.value):
            return f"super.{e.attr}"  # super().attr (verified convention)
        obj = self._expr(e.value)
        if obj == "this":
            # self.field -> bare m_x, self.method -> bare method (verified
            # convention: engine code accesses fields without `this.`)
            if e.attr in self._field_names:
                return self._field_id(e.attr)
            if e.attr in self._method_names:
                return self._method_id(e.attr)
        return f"{obj}.{e.attr}"

    def _const(self, e: ConstExpr) -> str:
        v = e.value
        if v is None:
            return "null"
        if v is True:
            return "true"
        if v is False:
            return "false"
        if isinstance(v, str):
            return f'"{_escape(v)}"'
        if isinstance(v, float):
            return repr(v)
        return str(v)

    def _p(self, e: Expr) -> str:
        if isinstance(e, (NameExpr, ConstExpr, AttributeExpr, CallExpr,
                          SubscriptExpr, ListExpr, JoinedStrExpr)):
            return self._expr(e)
        return f"({self._expr(e)})"

    def _expr_type(self, e: Expr) -> Optional[Type]:
        """Best-effort type lookup for expression nodes (set by sema)."""
        if isinstance(e, NameExpr):
            return self._locals.get(e.name)
        t = getattr(e, "type", None)
        if isinstance(t, Type):
            return t
        return None

    def _dict_types(self, d: DictExpr):
        kt = vt = None
        if d.items:
            k = getattr(d.items[0][0], "type", None)
            v = getattr(d.items[0][1], "type", None)
            kt = k if isinstance(k, Type) and not isinstance(k, ErrorType) else None
            vt = v if isinstance(v, Type) and not isinstance(v, ErrorType) else None
        return kt, vt

    def _field_default(self, t: Type) -> str:
        if isinstance(t, ScalarType):
            return {"int": "0", "float": "0.0", "bool": "false", "string": '""'}.get(t.name, "0")
        return "null"

    # ------------------------------------------------------------------
    # naming policy
    # ------------------------------------------------------------------
    def _type(self, t: Type) -> str:
        return t.render()

    def _type_id(self, name: str) -> str:
        return self._check(name)

    def _fn_id(self, name: str) -> str:
        out = _to_pascal(name) if self.policy == "camel" else name
        return self._check(out)

    def _method_id(self, name: str) -> str:
        return self._fn_id(name)

    def _var_id(self, name: str) -> str:
        if name == "this":  # deliberate keyword usage, never renamed
            return "this"
        out = _to_camel(name) if self.policy == "camel" else name
        return self._check(out)

    def _field_id(self, name: str) -> str:
        return self._check(self.field_prefix + _to_camel(name) if self.policy == "camel"
                           else self.field_prefix + name)

    def _check(self, ident: str) -> str:
        if ident in RESERVED:
            self.diag.warning(
                "reserved-word",
                f"identifier '{ident}' is reserved in EnforceScript; "
                f"renamed to '_{ident}'",
            )
            return "_" + ident
        return ident

    # ------------------------------------------------------------------
    def _line(self, text: str = "") -> None:
        if text:
            self.lines.append("    " * self.indent + text)
        else:
            self.lines.append("")

    def _emit_doc_comment(self, doc: str) -> None:
        for line in doc.strip().splitlines():
            self._line(f"// {line}")

    def _emit_todos(self, todos: List[str]) -> None:
        for t in todos:
            self._line(f"// TODO[{t}]")


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

def _is_simple(e: Expr) -> bool:
    return isinstance(e, (NameExpr, ConstExpr))


def _is_super_expr(e: Expr) -> bool:
    """True for `super()` (the call node, before an attribute access)."""
    return (isinstance(e, CallExpr)
            and isinstance(e.func, NameExpr)
            and e.func.name == "super"
            and not e.args
            and not e.kwargs)


def _escape(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return out


def _to_camel(name: str) -> str:
    head, _, tail = name.partition("_")
    return head + tail.title().replace("_", "")


def _to_pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def _convert_py_format(s: str):
    """Map Python old-style % placeholders (%s %d %f %r) to EnforceScript
    format() positional placeholders (%1, %2, ...). Returns (new_string, count)."""
    out: List[str] = []
    i = 0
    n = 0
    while i < len(s):
        ch = s[i]
        if ch == "%":
            if i + 1 < len(s) and s[i + 1] == "%":
                out.append("%")
                i += 2
                continue
            j = i + 1
            while j < len(s) and s[j] in "0123456789.-+ #hlL":
                j += 1
            if j < len(s) and s[j] in "sdifr":
                n += 1
                out.append(f"%{n}")
                i = j + 1
                continue
            out.append("%")
            i += 1
            continue
        out.append(ch)
        i += 1
    return "".join(out), n
