// Generated by any2enforce v0.1 -- DO NOT EDIT
// Source: demo.py (Python -> EnforceScript)

// Demo module: Python -> EnforceScript showcase for any2enforce v0.1.
// import math (math)

int add(int a, int b)
{
    return a + b;
}

string describe(int count, string label)
{
    auto text = string.Format("count=%1 label=%2", count, label);
    return text;
}

int total(array<int> values)
{
    auto result = 0;
    foreach (int v : values)
    {
        result += v;
    }
    return result;
}

void countdown(int n)
{
    for (int i = n; i > 0; i -= 1)
    {
        Print(i);
    }
}

void stats(array<float> values)
{
    auto highest = values[0];
    foreach (float v : values)
    {
        if (v > highest)
        {
            highest = v;
        }
    }
    Print(string.Format("max = %1", highest));
}

class Unit
{
    protected string m_name;
    protected int m_hp;

    void Unit(string name, int hp = 100)
    {
        m_name = name;
        m_hp = hp;
    }

    void damage(int dmg)
    {
        m_hp -= dmg;
    }

    void heal(int amount)
    {
        if ((m_hp + amount) > 100)
        {
            m_hp = 100;
        }
        else
        {
            m_hp += amount;
        }
    }

    static string kind()
    {
        return "unit";
    }
}

class Soldier : Unit
{
    protected string m_rank;  // was initialized to "private" in Python
    protected int m_ammo;  // was initialized to 30 in Python

    void Soldier(string name)
    {
        m_rank = "private";
        m_ammo = 30;
    }

    void reload()
    {
        m_ammo = 30;
    }
}
