// Generated by any2enforce v0.1 -- DO NOT EDIT
// Source: mlp_forward.py (Python -> EnforceScript)

// numpy-free MLP 前向 —— ANNA_DrivePolicyModel.c 的 round-trip 演示。
// 
// 架构与 ANNA 的 Hybrid Brain M2 完全同构：
//     features -> Standardize -> W1+B1 -> ReLU -> W2+B2 -> Softmax -> argmax
// 此处规模取 4->8->3 便于阅读；维度只是常量（ANNA 为 13->16->6，真实权重由
// 其 tools/sim/export_policy_constants.py 生成）。权重为占位示意值。
// 本文件全部使用 any2enforce v0.1 子集（纯循环 / list / 类型注解），
// 用于验证工具能把"算法层"代码转成与 ANNA 同风格的 EnforceScript。
float relu(float x)
{
    if (x > 0.0)
    {
        return x;
    }
    else
    {
        return 0.0;
    }
}

float approx_exp(float x)
{
    if (x < -20.0)
    {
        return 0.0;
    }
    if (x > 20.0)
    {
        return Math.Pow(2.718281828459045, 20.0);
    }
    return Math.Pow(2.718281828459045, x);
}

array<float> softmax(array<float> logits)
{
    auto count = logits.Count();
    auto max_logit = logits[0];
    for (int idx = 1; idx < count; idx++)
    {
        if (logits[idx] > max_logit)
        {
            max_logit = logits[idx];
        }
    }
    array<float> probs = {  };
    auto total = 0.0;
    for (int idx = 0; idx < count; idx++)
    {
        auto value = approx_exp(logits[idx] - max_logit);
        probs.Insert(value);
        total = total + value;
    }
    for (int idx = 0; idx < count; idx++)
    {
        probs[idx] = probs[idx] / total;
    }
    return probs;
}

int predict_behavior(array<float> features)
{
    array<float> means = { 0.05, -0.02, 0.3, 0.1 };
    array<float> scales = { 0.15, 0.1, 0.2, 0.13 };
    array<float> w1 = { -0.05, 0.43, -0.12, -0.36, 0.17, 0.25, 0.02, 0.08, -0.29, -0.29, -0.13, -0.02, 0.12, -0.03, 0.21, 0.05, -0.64, -0.17, 0.12, 0.43, -0.18, 0.22, 0.0, 0.33, -0.36, 0.44, -0.51, -0.45, -0.21, -0.33, 0.12, 0.13 };
    array<float> b1 = { -0.19, 0.56, 0.04, 0.66, -0.15, 0.23, 1.06, -0.07 };
    array<float> w2 = { -0.61, 0.95, 0.09, 0.92, -0.13, 0.56, 1.37, -0.38, 0.03, -0.27, 0.79, 0.3, 0.39, -0.01, -0.4, -0.0, 0.4, 0.11, -0.67, -0.04, 0.33, 0.55, 0.11, 0.41 };
    array<float> b2 = { 1.2, -0.18, -0.28 };
    auto feature_count = 4;
    auto hidden_size = 8;
    auto class_count = 3;
    array<float> x_norm = {  };
    for (int fi = 0; fi < feature_count; fi++)
    {
        auto scale = scales[fi];
        if (scale < 0.001)
        {
            scale = 0.001;
        }
        x_norm.Insert((features[fi] - means[fi]) / scale);
    }
    array<float> hidden = {  };
    for (int hi = 0; hi < hidden_size; hi++)
    {
        auto z = b1[hi];
        auto wbase = hi * feature_count;
        for (int fi = 0; fi < feature_count; fi++)
        {
            z = z + (w1[wbase + fi] * x_norm[fi]);
        }
        hidden.Insert(relu(z));
    }
    array<float> logits = {  };
    for (int ci = 0; ci < class_count; ci++)
    {
        auto z = b2[ci];
        auto wbase = ci * hidden_size;
        for (int hi = 0; hi < hidden_size; hi++)
        {
            z = z + (w2[wbase + hi] * hidden[hi]);
        }
        logits.Insert(z);
    }
    auto probs = softmax(logits);
    auto best_idx = 0;
    auto best_prob = probs[0];
    for (int idx = 1; idx < class_count; idx++)
    {
        if (probs[idx] > best_prob)
        {
            best_prob = probs[idx];
            best_idx = idx;
        }
    }
    return best_idx;
}
