// Generated by any2enforce v0.1 -- DO NOT EDIT
// Source: mlp_forward.py (Python -> EnforceScript)

// numpy-free MLP 前向 —— ANNA_DrivePolicyModel.c 的 round-trip 演示。
// 
// 架构与 ANNA 的 Hybrid Brain M2 完全同构：
//     features -> Standardize -> W1+B1 -> ReLU -> W2+B2 -> Softmax -> argmax
// 此处规模取 4->8->3 便于阅读；维度只是常量（ANNA 为 13->16->6，真实权重由
// 其 tools/sim/export_policy_constants.py 生成）。
// 
// 权重为**手工设计的判别式占位值**（保证不同输入命中不同类别，便于跨类别
// 数值对拍）：
//   hidden[0..7] = relu(±x0), relu(±x1), relu(±x2), relu(±x3)   （W1 为符号选择矩阵）
//   class0 = h0+h2+h4+h6（输入全正）、class1 = h1+h2（x0 负 x1 正）、
//   class2 = h5+h6（x2 负 x3 正）
// 期望（Python 参考已算好）：
//   [ 1, 1, 1, 1] -> 0     [-1, 1, 0, 0] -> 1     [ 0, 0,-1, 1] -> 2
//   [-1,-1,-1,-1] -> 1     [ 1,-1, 1,-1] -> 0     [ 0.5,-0.5,0,0] -> 0
// 
// 本文件全部使用 any2enforce v0.1 子集（纯循环 / list / 类型注解）。
float relu(float x)
{
    if (x > 0.0)
    {
        return x;
    }
    else
    {
        return 0.0;
    }
}

float approx_exp(float x)
{
    if (x < -20.0)
    {
        return 0.0;
    }
    if (x > 20.0)
    {
        return Math.Pow(2.718281828459045, 20.0);
    }
    return Math.Pow(2.718281828459045, x);
}

array<float> softmax(array<float> logits)
{
    auto count = logits.Count();
    auto max_logit = logits[0];
    for (int idx = 1; idx < count; idx++)
    {
        if (logits[idx] > max_logit)
        {
            max_logit = logits[idx];
        }
    }
    array<float> probs = {  };
    auto total = 0.0;
    for (int idx = 0; idx < count; idx++)
    {
        auto value = approx_exp(logits[idx] - max_logit);
        probs.Insert(value);
        total = total + value;
    }
    for (int idx = 0; idx < count; idx++)
    {
        probs[idx] = probs[idx] / total;
    }
    return probs;
}

int predict_behavior(array<float> features)
{
    array<float> means = { 0.0, 0.0, 0.0, 0.0 };
    array<float> scales = { 1.0, 1.0, 1.0, 1.0 };
    array<float> w1 = { 1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, -1.0 };
    array<float> b1 = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
    array<float> w2 = { 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0 };
    array<float> b2 = { 0.0, 0.0, 0.0 };
    auto feature_count = 4;
    auto hidden_size = 8;
    auto class_count = 3;
    array<float> x_norm = {  };
    for (int fi = 0; fi < feature_count; fi++)
    {
        auto scale = scales[fi];
        if (scale < 0.001)
        {
            scale = 0.001;
        }
        x_norm.Insert((features[fi] - means[fi]) / scale);
    }
    array<float> hidden = {  };
    for (int hi = 0; hi < hidden_size; hi++)
    {
        auto z = b1[hi];
        auto wbase = hi * feature_count;
        for (int fi = 0; fi < feature_count; fi++)
        {
            z = z + (w1[wbase + fi] * x_norm[fi]);
        }
        hidden.Insert(relu(z));
    }
    array<float> logits = {  };
    for (int ci = 0; ci < class_count; ci++)
    {
        auto z = b2[ci];
        auto wbase = ci * hidden_size;
        for (int hi = 0; hi < hidden_size; hi++)
        {
            z = z + (w2[wbase + hi] * hidden[hi]);
        }
        logits.Insert(z);
    }
    auto probs = softmax(logits);
    auto best_idx = 0;
    auto best_prob = probs[0];
    for (int idx = 1; idx < class_count; idx++)
    {
        if (probs[idx] > best_prob)
        {
            best_prob = probs[idx];
            best_idx = idx;
        }
    }
    return best_idx;
}
