// Generated by any2enforce v0.1 -- DO NOT EDIT
// Source: training_lab.py (Python -> EnforceScript)

// AI 训练实验室 POC —— 游戏内现场学会"追目标"。
// 
// 纯脚本虚拟沙盒（无需实体/prefab）：目标在虚拟平面上做之字形运动，
// 学员（4->8->4 MLP）通过模仿 teacher 规则（向主导轴方向追击）在线学习，
// 实时打印三类指标：loss 下降、准确率上升、追击误差缩小。
// 跑通后接入真实实体只需把 lab_predict / lab_train_step 的输入换成实体坐标
// （见 training_lab_glue.c）。
// 
// 运行：转换后 execCode lab_run()。
// 全部使用 any2enforce v0.1 子集；全局函数统一 lab_ 前缀（扁平命名空间）。
float lab_relu(float x)
{
    if (x > 0.0)
    {
        return x;
    }
    else
    {
        return 0.0;
    }
}

float lab_exp(float x)
{
    if (x < -20.0)
    {
        return 0.0;
    }
    if (x > 20.0)
    {
        return Math.Pow(2.718281828459045, 20.0);
    }
    return Math.Pow(2.718281828459045, x);
}

array<float> lab_softmax(array<float> logits)
{
    auto count = logits.Count();
    auto max_logit = logits[0];
    for (int idx = 1; idx < count; idx++)
    {
        if (logits[idx] > max_logit)
        {
            max_logit = logits[idx];
        }
    }
    array<float> probs = {  };
    auto total = 0.0;
    for (int idx = 0; idx < count; idx++)
    {
        auto value = lab_exp(logits[idx] - max_logit);
        probs.Insert(value);
        total = total + value;
    }
    for (int idx = 0; idx < count; idx++)
    {
        probs[idx] = probs[idx] / total;
    }
    return probs;
}

// LCG 伪随机初始化（float 取模，跨语言数值一致）。
void lab_init(array<float> w1, array<float> b1, array<float> w2, array<float> b2)
{
    auto seed = 0.5;
    for (int i = 0; i < 32; i++)
    {
        seed = Math.Mod(((seed * 1.732) + 3.14159), 97.0);
        w1.Insert((seed / 97.0) - 0.5);
    }
    for (int i = 0; i < 8; i++)
    {
        seed = Math.Mod(((seed * 1.732) + 3.14159), 97.0);
        b1.Insert((seed / 97.0) - 0.5);
    }
    for (int i = 0; i < 32; i++)
    {
        seed = Math.Mod(((seed * 1.732) + 3.14159), 97.0);
        w2.Insert((seed / 97.0) - 0.5);
    }
    for (int i = 0; i < 4; i++)
    {
        seed = Math.Mod(((seed * 1.732) + 3.14159), 97.0);
        b2.Insert((seed / 97.0) - 0.5);
    }
}

// 4 特征 -> 8 隐层 -> 4 类 softmax 概率。
array<float> lab_forward(array<float> x, array<float> w1, array<float> b1, array<float> w2, array<float> b2)
{
    array<float> h = {  };
    for (int hi = 0; hi < 8; hi++)
    {
        auto z = b1[hi];
        auto wbase = hi * 4;
        for (int fi = 0; fi < 4; fi++)
        {
            z = z + (w1[wbase + fi] * x[fi]);
        }
        h.Insert(lab_relu(z));
    }
    array<float> z2 = {  };
    for (int ci = 0; ci < 4; ci++)
    {
        auto z = b2[ci];
        auto wbase = ci * 8;
        for (int hi = 0; hi < 8; hi++)
        {
            z = z + (w2[wbase + hi] * h[hi]);
        }
        z2.Insert(z);
    }
    return lab_softmax(z2);
}

// 单样本：前向 + MSE + 反向传播 + SGD。返回样本 loss。
float lab_train_step(array<float> x, array<float> y, array<float> w1, array<float> b1, array<float> w2, array<float> b2, float lr)
{
    array<float> z1 = {  };
    array<float> h1 = {  };
    for (int hi = 0; hi < 8; hi++)
    {
        auto z = b1[hi];
        auto wbase = hi * 4;
        for (int fi = 0; fi < 4; fi++)
        {
            z = z + (w1[wbase + fi] * x[fi]);
        }
        z1.Insert(z);
        h1.Insert(lab_relu(z));
    }
    array<float> z2 = {  };
    for (int ci = 0; ci < 4; ci++)
    {
        auto z = b2[ci];
        auto wbase = ci * 8;
        for (int hi = 0; hi < 8; hi++)
        {
            z = z + (w2[wbase + hi] * h1[hi]);
        }
        z2.Insert(z);
    }
    auto probs = lab_softmax(z2);
    array<float> err = {  };
    auto loss = 0.0;
    for (int ci = 0; ci < 4; ci++)
    {
        auto e = probs[ci] - y[ci];
        err.Insert(e);
        loss = loss + (e * e);
    }
    array<float> dh = {  };
    for (int hi = 0; hi < 8; hi++)
    {
        auto g = 0.0;
        for (int ci = 0; ci < 4; ci++)
        {
            g = g + (w2[(ci * 8) + hi] * err[ci]);
        }
        dh.Insert(g);
    }
    for (int ci = 0; ci < 4; ci++)
    {
        b2[ci] = b2[ci] - (lr * err[ci]);
        auto wbase = ci * 8;
        for (int hi = 0; hi < 8; hi++)
        {
            w2[wbase + hi] = w2[wbase + hi] - ((lr * err[ci]) * h1[hi]);
        }
    }
    for (int hi = 0; hi < 8; hi++)
    {
        auto g = dh[hi];
        if (z1[hi] <= 0.0)
        {
            g = 0.0;
        }
        if (g > 1.0)
        {
            g = 1.0;
        }
        if (g < -1.0)
        {
            g = -1.0;
        }
        b1[hi] = b1[hi] - (lr * g);
        auto wbase = hi * 4;
        for (int fi = 0; fi < 4; fi++)
        {
            w1[wbase + fi] = w1[wbase + fi] - ((lr * g) * x[fi]);
        }
    }
    return loss;
}

// 规则 teacher：向相对位移的主导轴方向追击。
//     类：0=-x, 1=+x, 2=-y, 3=+y。
int lab_teacher(float dx, float dy)
{
    auto ax = dx;
    if (ax < 0.0)
    {
        ax = -dx;
    }
    auto ay = dy;
    if (ay < 0.0)
    {
        ay = -dy;
    }
    if (ax > ay)
    {
        if (dx > 0.0)
        {
            return 1;
        }
        return 0;
    }
    if (dy > 0.0)
    {
        return 3;
    }
    return 2;
}

void lab_run()
{
    auto lr = 0.1;
    array<float> buf_x = {  };
    array<float> buf_y = {  };
    array<int> labels = {  };
    array<float> w1 = {  };
    array<float> b1 = {  };
    array<float> w2 = {  };
    array<float> b2 = {  };
    lab_init(w1, b1, w2, b2);
    auto cx = 0.0;
    auto cy = 0.0;
    auto tx = 30.0;
    auto ty = -20.0;
    for (int step = 0; step < 400; step++)
    {
        tx = tx + 1.2;
        if (tx > 50.0)
        {
            tx = -50.0;
        }
        ty = ty - 0.8;
        if (ty < -40.0)
        {
            ty = 40.0;
        }
        auto dx = tx - cx;
        auto dy = ty - cy;
        array<float> feat = {  };
        feat.Insert(dx / 100.0);
        feat.Insert(dy / 100.0);
        feat.Insert(1.0);
        feat.Insert(0.0);
        if (step < 200)
        {
            auto best = lab_teacher(dx, dy);
        }
        else
        {
            auto probs = lab_forward(feat, w1, b1, w2, b2);
            auto best = 0;
            auto bestp = probs[0];
            for (int ci = 1; ci < 4; ci++)
            {
                if (probs[ci] > bestp)
                {
                    bestp = probs[ci];
                    best = ci;
                }
            }
        }
        if (best == 0)
        {
            cx = cx - 2.0;
        }
        else if (best == 1)
        {
            cx = cx + 2.0;
        }
        else if (best == 2)
        {
            cy = cy - 2.0;
        }
        else
        {
            cy = cy + 2.0;
        }
        if (cx > 55.0)
        {
            cx = 55.0;
        }
        if (cx < -55.0)
        {
            cx = -55.0;
        }
        if (cy > 45.0)
        {
            cy = 45.0;
        }
        if (cy < -45.0)
        {
            cy = -45.0;
        }
        auto label = lab_teacher(dx, dy);
        buf_x.Insert(dx / 100.0);
        buf_x.Insert(dy / 100.0);
        buf_x.Insert(1.0);
        buf_x.Insert(0.0);
        buf_y.Insert(0.0);
        buf_y.Insert(0.0);
        buf_y.Insert(0.0);
        buf_y.Insert(0.0);
        buf_y[(buf_y.Count() - 4) + label] = 1.0;
        labels.Insert(label);
        if ((step > 0) && ((step % 20) == 0))
        {
            auto n = labels.Count();
            auto loss_sum = 0.0;
            auto acc = 0;
            for (int s = 0; s < n; s++)
            {
                array<float> smp = {  };
                smp.Insert(buf_x[(s * 4) + 0]);
                smp.Insert(buf_x[(s * 4) + 1]);
                smp.Insert(buf_x[(s * 4) + 2]);
                smp.Insert(buf_x[(s * 4) + 3]);
                array<float> yoh = {  };
                yoh.Insert(buf_y[(s * 4) + 0]);
                yoh.Insert(buf_y[(s * 4) + 1]);
                yoh.Insert(buf_y[(s * 4) + 2]);
                yoh.Insert(buf_y[(s * 4) + 3]);
                for (int e = 0; e < 16; e++)
                {
                    loss_sum = loss_sum + lab_train_step(smp, yoh, w1, b1, w2, b2, lr);
                }
                auto p2 = lab_forward(smp, w1, b1, w2, b2);
                auto bp = 0;
                auto bv = p2[0];
                for (int ci = 1; ci < 4; ci++)
                {
                    if (p2[ci] > bv)
                    {
                        bv = p2[ci];
                        bp = ci;
                    }
                }
                if (bp == labels[s])
                {
                    acc = acc + 1;
                }
            }
            auto err = dx;
            if (err < 0.0)
            {
                err = -dx;
            }
            auto ey = dy;
            if (ey < 0.0)
            {
                ey = -dy;
            }
            PrintFormat("%1 %2 %3 %4", step, loss_sum / (n * 8), (acc * 100) / n, err + ey);
        }
    }
}
