// Generated by any2enforce v0.1 -- DO NOT EDIT
// Source: train_mlp.py (Python -> EnforceScript)

// 游戏内自训练 POC：4→8→3 MLP 在线训练（手写前向 + 反向传播 + SGD）。
// 
// 全部使用 any2enforce v0.1 子集（纯循环 / list / 注解 / 全局函数）。
// 训练数据为内置 8 样本 3 类任务（one-hot）；权重用 LCG 伪随机初始化
// （float 取模，Python 与 EnforceScript 的 IEEE 结果一致）。
// 运行：转换后用 execCode run_training()，应打印 30 轮单调下降的 loss。
// 验证：本文件在 Python 里先跑通（loss 下降），再转成 EnforceScript 对拍。
// 
// ⚠ 命名空间教训：EnforceScript 无模块，全部脚本一起编译 —— 全局函数名
// 必须全项目唯一（与 mlp_forward.c 的 relu/softmax 撞名会报
// "Multiple declaration of function"）。故辅助函数统一加 train_ 前缀；
// 工具侧可用 --prefix 选项统一加前缀。
float train_relu(float x)
{
    if (x > 0.0)
    {
        return x;
    }
    else
    {
        return 0.0;
    }
}

float train_relu_deriv(float x)
{
    if (x > 0.0)
    {
        return 1.0;
    }
    else
    {
        return 0.0;
    }
}

float train_approx_exp(float x)
{
    if (x < -20.0)
    {
        return 0.0;
    }
    if (x > 20.0)
    {
        return Math.Pow(2.718281828459045, 20.0);
    }
    return Math.Pow(2.718281828459045, x);
}

array<float> train_softmax(array<float> logits)
{
    auto count = logits.Count();
    auto max_logit = logits[0];
    for (int idx = 1; idx < count; idx++)
    {
        if (logits[idx] > max_logit)
        {
            max_logit = logits[idx];
        }
    }
    array<float> probs = {  };
    auto total = 0.0;
    for (int idx = 0; idx < count; idx++)
    {
        auto value = train_approx_exp(logits[idx] - max_logit);
        probs.Insert(value);
        total = total + value;
    }
    for (int idx = 0; idx < count; idx++)
    {
        probs[idx] = probs[idx] / total;
    }
    return probs;
}

// LCG 伪随机初始化（float 取模，跨语言数值一致）。
void init_weights(array<float> w1, array<float> b1, array<float> w2, array<float> b2)
{
    auto seed = 0.5;
    for (int i = 0; i < 32; i++)
    {
        seed = Math.Mod(((seed * 1.732) + 3.14159), 97.0);
        w1.Insert((seed / 97.0) - 0.5);
    }
    for (int i = 0; i < 8; i++)
    {
        seed = Math.Mod(((seed * 1.732) + 3.14159), 97.0);
        b1.Insert((seed / 97.0) - 0.5);
    }
    for (int i = 0; i < 24; i++)
    {
        seed = Math.Mod(((seed * 1.732) + 3.14159), 97.0);
        w2.Insert((seed / 97.0) - 0.5);
    }
    for (int i = 0; i < 3; i++)
    {
        seed = Math.Mod(((seed * 1.732) + 3.14159), 97.0);
        b2.Insert((seed / 97.0) - 0.5);
    }
}

// 一个 epoch：前向 -> MSE loss -> 反向传播 -> SGD 更新。返回平均 loss。
float train_epoch(array<float> xs, array<float> ys, array<float> w1, array<float> b1, array<float> w2, array<float> b2, int sample_count, float lr, int feature_count, int hidden_size, int class_count)
{
    auto total_loss = 0.0;
    for (int s = 0; s < sample_count; s++)
    {
        array<float> x_norm = {  };
        array<float> z1 = {  };
        array<float> h1 = {  };
        for (int fi = 0; fi < feature_count; fi++)
        {
            x_norm.Insert(xs[(s * feature_count) + fi]);
        }
        int wbase = 0;
        float z = 0.0;
        for (int hi = 0; hi < hidden_size; hi++)
        {
            z = b1[hi];
            wbase = hi * feature_count;
            for (int fi = 0; fi < feature_count; fi++)
            {
                z = z + (w1[wbase + fi] * x_norm[fi]);
            }
            z1.Insert(z);
            h1.Insert(train_relu(z));
        }
        array<float> z2 = {  };
        for (int ci = 0; ci < class_count; ci++)
        {
            z = b2[ci];
            wbase = ci * hidden_size;
            for (int hi = 0; hi < hidden_size; hi++)
            {
                z = z + (w2[wbase + hi] * h1[hi]);
            }
            z2.Insert(z);
        }
        auto probs = train_softmax(z2);
        array<float> err = {  };
        for (int ci = 0; ci < class_count; ci++)
        {
            auto e = probs[ci] - ys[(s * class_count) + ci];
            err.Insert(e);
            total_loss = total_loss + (e * e);
        }
        array<float> dh = {  };
        float g = 0.0;
        for (int hi = 0; hi < hidden_size; hi++)
        {
            g = 0.0;
            for (int ci = 0; ci < class_count; ci++)
            {
                g = g + (w2[(ci * hidden_size) + hi] * err[ci]);
            }
            dh.Insert(g);
        }
        for (int ci = 0; ci < class_count; ci++)
        {
            b2[ci] = b2[ci] - (lr * err[ci]);
            wbase = ci * hidden_size;
            for (int hi = 0; hi < hidden_size; hi++)
            {
                w2[wbase + hi] = w2[wbase + hi] - ((lr * err[ci]) * h1[hi]);
            }
        }
        for (int hi = 0; hi < hidden_size; hi++)
        {
            g = dh[hi] * train_relu_deriv(z1[hi]);
            b1[hi] = b1[hi] - (lr * g);
            wbase = hi * feature_count;
            for (int fi = 0; fi < feature_count; fi++)
            {
                w1[wbase + fi] = w1[wbase + fi] - ((lr * g) * x_norm[fi]);
            }
        }
    }
    return total_loss / sample_count;
}

void run_training()
{
    auto feature_count = 4;
    auto hidden_size = 8;
    auto class_count = 3;
    auto sample_count = 8;
    auto lr = 0.5;
    auto epochs = 30;
    array<float> xs = { 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 0.5, -0.5, 0.0, 0.0, 0.1, -0.05, 0.4, 0.2, 0.9, -0.8, 0.7, 0.3 };
    array<float> ys = { 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0 };
    array<float> w1 = {  };
    array<float> b1 = {  };
    array<float> w2 = {  };
    array<float> b2 = {  };
    init_weights(w1, b1, w2, b2);
    for (int epoch = 0; epoch < epochs; epoch++)
    {
        auto loss = train_epoch(xs, ys, w1, b1, w2, b2, sample_count, lr, feature_count, hidden_size, class_count);
        PrintFormat("%1 %2", epoch, loss);
    }
}
