// Generated by any2enforce v0.1 -- DO NOT EDIT
// Source: calibrated.py (Python -> EnforceScript)

// Mappings calibrated against the real Reforger scripts corpus
// (C:\Users\74738\Desktop\_reforger_code_full_v2\scripts).
int pick(int a, int b)
{
    if (a > b)
    {
        return a;
    }
    else
    {
        return b;
    }
}

void extremes(array<int> values)
{
    auto lo = values[0];
    auto hi = values[0];
    foreach (int v : values)
    {
        lo = Math.MinInt(lo, v);
        hi = Math.MaxInt(hi, v);
    }
    auto diff = hi - lo;
    auto sign = Math.AbsInt(diff);
    PrintFormat("%1 %2", "range", sign);
}

map<string, int> make_config()
{
    map<string, int> cfg = new map<string, int>();
    cfg["a"] = 1;
    cfg["b"] = 2;
    cfg["c"] = 3;
    return cfg;
}

array<string> names()
{
    array<string> result = { "alice", "bob" };
    return result;
}

bool is_member(array<int> values, int probe)
{
    return values.Contains(probe);
}

bool not_member(array<int> values, int probe)
{
    return !values.Contains(probe);
}

float wrap(float deg)
{
    return Math.Mod(deg, 360.0);
}
